# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(build.artifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '64ca1e9f-9723-4d44-b9c3-e1e7edfb6115/b8d6dbb9-0ada-4579-885f-c6c5c52c4732'
    vstsFeedPackagePublish: 'heamr'
    versionOption: 'patch'
    publishedPackageVar: 'd'

